CREATE DATABASE IF NOT EXISTS crypto_tax;
USE crypto_tax;

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(10) NOT NULL,
  coin VARCHAR(10) NOT NULL,
  amount DECIMAL(18,8) NOT NULL,
  price DECIMAL(18,2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);